# Generated by Django 5.1.2 on 2024-11-02 23:44

import django_prometheus.models
import music.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="albums",
            name="description",
            field=models.CharField(
                blank=True, default=None, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="genres",
            name="image",
            field=models.ImageField(
                default=None,
                storage=music.models._get_public_media_storage,
                upload_to=music.models._upload_genres_to,
                verbose_name="Ссылка на изображение жанра",
            ),
        ),
        migrations.AddField(
            model_name="tracks",
            name="description",
            field=models.CharField(
                blank=True, default=None, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="albums",
            name="cover_image",
            field=models.ImageField(
                storage=music.models._get_public_media_storage,
                upload_to=music.models._upload_albums_to,
                verbose_name="Ссылка на изображение",
            ),
        ),
        migrations.AlterField(
            model_name="albums",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="artists",
            name="avatar_url",
            field=models.ImageField(
                storage=music.models._get_public_media_storage,
                upload_to=music.models._upload_artists_to,
                verbose_name="Ссылка на аватар",
            ),
        ),
        migrations.AlterField(
            model_name="artists",
            name="description",
            field=models.CharField(default=None, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="artists",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="genres",
            name="description",
            field=models.CharField(
                blank=True, default=None, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="genres",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="labels",
            name="cover_image",
            field=models.ImageField(
                storage=music.models._get_public_media_storage,
                upload_to=music.models._upload_labels_to,
                verbose_name="Ссылка на изображение",
            ),
        ),
        migrations.AlterField(
            model_name="labels",
            name="description",
            field=models.CharField(default=None, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="labels",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="tracks",
            name="cover_image",
            field=models.ImageField(
                storage=music.models._get_public_media_storage,
                upload_to=music.models._upload_tracks_to,
                verbose_name="Ссылка на изображение",
            ),
        ),
        migrations.AlterField(
            model_name="tracks",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="tracks",
            name="track",
            field=models.FileField(
                storage=music.models._get_public_media_storage,
                upload_to=music.models._upload_labels_to,
                verbose_name="Ссылка на трек",
            ),
        ),
        migrations.CreateModel(
            name="GeneratedImageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=music.models._get_public_media_storage,
                        upload_to=music.models._upload_images_to,
                        verbose_name="Ссылка на сгенерированное изображение",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["-created", "-updated"],
                        name="music_gener_created_52ea44_idx",
                    )
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("gen_image"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="GeneratedVideoContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления"
                    ),
                ),
                ("duration", models.DurationField(verbose_name="Длительность")),
                (
                    "video",
                    models.FileField(
                        storage=music.models._get_public_media_storage,
                        upload_to=music.models._upload_videos_to,
                        verbose_name="Ссылка на сгенерированное видео",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["-created", "-updated"],
                        name="music_gener_created_2f453a_idx",
                    )
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("gen_video"),
                models.Model,
            ),
        ),
    ]
