# Generated by Django 5.1.2 on 2024-10-30 23:25

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='image',
            field=models.ImageField(default=None, upload_to='genres', verbose_name='Ссылка на изображение жанра'),
        ),
        migrations.CreateModel(
            name='GeneratedImageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Ссылка на сгенерированное изображение')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name', '-created', '-updated'], name='music_gener_name_5bc66e_idx')],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('gen_image'), models.Model),
        ),
        migrations.CreateModel(
            name='GeneratedVideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('duration', models.DurationField(verbose_name='Длительность')),
                ('video', models.FileField(upload_to='', verbose_name='Ссылка на сгенерированное видео')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name', '-created', '-updated'], name='music_gener_name_f3a338_idx')],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('gen_video'), models.Model),
        ),
    ]
