# Generated by Django 5.1.3 on 2024-11-30 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_audio_audio_alter_images_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgenres', to='music.genres'),
        ),
    ]
