# Generated by Django 5.1.4 on 2024-12-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_artists_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='bio',
            field=models.TextField(null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
