# Generated by Django 5.1.5 on 2025-01-26 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0012_releases_remove_albums_artists_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labels",
            name="cover_image",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="music.images", verbose_name="Изображение"
            ),
        ),
    ]
