# Generated by Django 5.1.5 on 2025-01-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0013_alter_labels_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genres",
            name="cover_image",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="music.images", verbose_name="Изображение"
            ),
        ),
    ]
