# Generated by Django 5.1.5 on 2025-01-27 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0016_alter_releases_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracks",
            name="video",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="music.video", verbose_name="Видео"
            ),
        ),
    ]
