# Generated by Django 5.1.5 on 2025-01-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_tracks_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracks',
            old_name='album',
            new_name='release',
        ),
    ]
