# Generated by Django 5.1.5 on 2025-02-01 21:56

import pictures.models
from django.db import migrations, models

import apps.music.models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0018_rename_album_tracks_release"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="audio",
            field=models.FileField(
                max_length=1024,
                storage=apps.music.models._get_public_media_storage,
                upload_to=apps.music.models._upload_audio_to,
                verbose_name="Ссылка на аудио",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="image",
            field=pictures.models.PictureField(
                aspect_ratios=[None],
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                default=None,
                file_types=["WEBP"],
                grid_columns=12,
                height_field="image_height",
                max_length=1024,
                pixel_densities=[1, 2],
                storage=apps.music.models._get_public_media_storage,
                upload_to=apps.music.models._upload_images_to,
                verbose_name="Ссылка на изображение",
                width_field="image_width",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(
                max_length=1024,
                storage=apps.music.models._get_public_media_storage,
                upload_to=apps.music.models._upload_videos_to,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
