# Generated by Django 5.1.5 on 2025-02-23 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0020_tracks_age_related_content_tracks_publication_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracks",
            name="cover_image",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="music.images", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="tracks",
            name="release",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="music.releases", verbose_name="Релиз трека"
            ),
        ),
    ]
