# Generated by Django 5.1.5 on 2025-02-23 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0021_alter_tracks_cover_image_alter_tracks_release"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracks",
            name="label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="music.labels", verbose_name="Лейбл"
            ),
        ),
    ]
